name: VAR.js running inside its own project!
on:
  - push
  - pull_request
jobs:
  lint:
    name: Linting VAR project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          SCRIPT: "format"
  test:
    name: Testing VAR project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          SCRIPT: "test"
  build:
    name: Building VAR project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          SCRIPT: "build"
