name: VAR.js running inside it own project!
on: push
jobs:
  lint:
    name: Linting VAR project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .
        with:
          SCRIPT: "format"
  test:
    name: Linting VAR project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .
        with:
          SCRIPT: "test"
  build:
    name: Linting VAR project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .
        with:
          SCRIPT: "build"
